name: viewpager
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
  
    ####packages
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2


    #Functional programming things
  dartz: ^0.10.1

    #Value equality
  equatable: ^2.0.3   #compare two instances of the same class?
    #Service locator
  get_it: ^7.2.0  #depInjection
    #Remote API
  internet_connection_checker: ^0.0.1+3   #chech ther is connection or note
  http: ^0.13.4 #reqyestes api
    #Local cashe
  shared_preferences: ^2.0.13
  animated_segmented_tab_control: ^1.0.1
  slide_switcher: ^1.1.2 



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

